# Generated by Django 4.2.2 on 2023-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_user_group'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
