# Generated by Django 4.2.2 on 2023-06-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='име'),
        ),
        migrations.AddField(
            model_name='camera',
            name='zone',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green')], default='green', max_length=244),
            preserve_default=False,
        ),
    ]
