# Generated by Django 4.2.2 on 2023-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_camera_name_camera_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='address',
            field=models.CharField(blank=True, null=True, verbose_name='адрес'),
        ),
    ]
