# Generated by Django 4.2.2 on 2023-06-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='rotation',
        ),
    ]
