# Generated by Django 4.2.2 on 2023-06-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_alter_camera_parking_mask_alter_camera_violator_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='organization',
        ),
    ]
