# Generated by Django 4.2.2 on 2023-06-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_remove_camera_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='parking_mask',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='violator_mask',
        ),
        migrations.AddField(
            model_name='camera',
            name='p_mask',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='v_mask',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
