# Generated by Django 4.2.2 on 2023-06-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_remove_camera_parking_mask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='height',
            field=models.CharField(blank=True, default=400, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='width',
            field=models.CharField(blank=True, default=200, null=True),
        ),
    ]
