# Generated by Django 4.2.2 on 2023-06-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_camera_height_camera_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='intruders_count',
            field=models.IntegerField(default=0),
        ),
    ]
